---
# This playbook deploys a simple standalone Tomcat 7 server.
#this will install tomcat
- hosts: appServers
  become: yes
  roles:
   - common
   - tomcat
- hosts: all
  become: yes
  roles:
   - common
